services:
  web-server:
    build: ./apache
    volumes:
      - ../src:/var/www
      - ./apache/apache-conf/:/etc/apache2/sites-enabled/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

  database:
    build: ./database
    environment:
      - MYSQL_DATABASE=sosed
      - MYSQL_ROOT_PASSWORD=951753
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - data:/var/lib/mysql

  test-database:
    build: ./database
    environment:
      - MYSQL_DATABASE=sosed_test
      - MYSQL_ROOT_PASSWORD=951753
    ports:
      - "3307:3306"
    networks:
      - internal
    volumes:
      - data-test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=host.docker.internal
    restart: always
    ports:
      - 8080:80
    networks:
      - internal

volumes:
    data:
    data-test:

networks:
  internal: